/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.hybridcompute.v2019_03_18;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.microsoft.rest.serializer.JsonFlatten;

/**
 * Describes a hybrid machine Update.
 */
@JsonFlatten
public class MachineUpdate extends UpdateResource {
    /**
     * The identity type.
     */
    @JsonProperty(value = "identity.type")
    private String type;

    /**
     * The identity's principal id.
     */
    @JsonProperty(value = "identity.principalId", access = JsonProperty.Access.WRITE_ONLY)
    private String principalId;

    /**
     * The identity's tenant id.
     */
    @JsonProperty(value = "identity.tenantId", access = JsonProperty.Access.WRITE_ONLY)
    private String tenantId;

    /**
     * Resource's Physical Location.
     */
    @JsonProperty(value = "properties.physicalLocation")
    private String physicalLocation;

    /**
     * Get the identity type.
     *
     * @return the type value
     */
    public String type() {
        return this.type;
    }

    /**
     * Set the identity type.
     *
     * @param type the type value to set
     * @return the MachineUpdate object itself.
     */
    public MachineUpdate withType(String type) {
        this.type = type;
        return this;
    }

    /**
     * Get the identity's principal id.
     *
     * @return the principalId value
     */
    public String principalId() {
        return this.principalId;
    }

    /**
     * Get the identity's tenant id.
     *
     * @return the tenantId value
     */
    public String tenantId() {
        return this.tenantId;
    }

    /**
     * Get resource's Physical Location.
     *
     * @return the physicalLocation value
     */
    public String physicalLocation() {
        return this.physicalLocation;
    }

    /**
     * Set resource's Physical Location.
     *
     * @param physicalLocation the physicalLocation value to set
     * @return the MachineUpdate object itself.
     */
    public MachineUpdate withPhysicalLocation(String physicalLocation) {
        this.physicalLocation = physicalLocation;
        return this;
    }

}
