/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.hybridcompute.v2019_03_18;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Defines values for StatusTypes.
 */
public enum StatusTypes {
    /** Enum value Connected. */
    CONNECTED("Connected"),

    /** Enum value Disconnected. */
    DISCONNECTED("Disconnected"),

    /** Enum value Error. */
    ERROR("Error");

    /** The actual serialized value for a StatusTypes instance. */
    private String value;

    StatusTypes(String value) {
        this.value = value;
    }

    /**
     * Parses a serialized value to a StatusTypes instance.
     *
     * @param value the serialized value to parse.
     * @return the parsed StatusTypes object, or null if unable to parse.
     */
    @JsonCreator
    public static StatusTypes fromString(String value) {
        StatusTypes[] items = StatusTypes.values();
        for (StatusTypes item : items) {
            if (item.toString().equalsIgnoreCase(value)) {
                return item;
            }
        }
        return null;
    }

    @JsonValue
    @Override
    public String toString() {
        return this.value;
    }
}
