/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.azurestack.v2017_06_01;

import rx.Observable;
import com.microsoft.azure.management.azurestack.v2017_06_01.implementation.GetProductsInner;
import com.microsoft.azure.arm.model.HasInner;

/**
 * Type representing GetProducts.
 */
public interface GetProducts extends HasInner<GetProductsInner> {
    /**
     * Returns a list of products.
     *
     * @param resourceGroup Name of the resource group.
     * @param registrationName Name of the Azure Stack registration.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable for the request
     */
    Observable<ProductList> listAsync(String resourceGroup, String registrationName);

}
