/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.vmwarecloudsimple.v2019_04_01;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The CustomizationIPSettings model.
 */
public class CustomizationIPSettings {
    /**
     * The list of gateways.
     */
    @JsonProperty(value = "gateway")
    private List<String> gateway;

    /**
     * Ip address customization settings.
     */
    @JsonProperty(value = "ip")
    private CustomizationIPAddress ip;

    /**
     * Adapter subnet mask.
     */
    @JsonProperty(value = "subnetMask")
    private String subnetMask;

    /**
     * Get the list of gateways.
     *
     * @return the gateway value
     */
    public List<String> gateway() {
        return this.gateway;
    }

    /**
     * Set the list of gateways.
     *
     * @param gateway the gateway value to set
     * @return the CustomizationIPSettings object itself.
     */
    public CustomizationIPSettings withGateway(List<String> gateway) {
        this.gateway = gateway;
        return this;
    }

    /**
     * Get ip address customization settings.
     *
     * @return the ip value
     */
    public CustomizationIPAddress ip() {
        return this.ip;
    }

    /**
     * Set ip address customization settings.
     *
     * @param ip the ip value to set
     * @return the CustomizationIPSettings object itself.
     */
    public CustomizationIPSettings withIp(CustomizationIPAddress ip) {
        this.ip = ip;
        return this;
    }

    /**
     * Get adapter subnet mask.
     *
     * @return the subnetMask value
     */
    public String subnetMask() {
        return this.subnetMask;
    }

    /**
     * Set adapter subnet mask.
     *
     * @param subnetMask the subnetMask value to set
     * @return the CustomizationIPSettings object itself.
     */
    public CustomizationIPSettings withSubnetMask(String subnetMask) {
        this.subnetMask = subnetMask;
        return this;
    }

}
