/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.vmwarecloudsimple.v2019_04_01;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The CustomizationNicSetting model.
 */
public class CustomizationNicSetting {
    /**
     * The list of adapters' settings.
     */
    @JsonProperty(value = "adapter")
    private CustomizationIPSettings adapter;

    /**
     * NIC mac address.
     */
    @JsonProperty(value = "macAddress")
    private String macAddress;

    /**
     * Get the list of adapters' settings.
     *
     * @return the adapter value
     */
    public CustomizationIPSettings adapter() {
        return this.adapter;
    }

    /**
     * Set the list of adapters' settings.
     *
     * @param adapter the adapter value to set
     * @return the CustomizationNicSetting object itself.
     */
    public CustomizationNicSetting withAdapter(CustomizationIPSettings adapter) {
        this.adapter = adapter;
        return this;
    }

    /**
     * Get nIC mac address.
     *
     * @return the macAddress value
     */
    public String macAddress() {
        return this.macAddress;
    }

    /**
     * Set nIC mac address.
     *
     * @param macAddress the macAddress value to set
     * @return the CustomizationNicSetting object itself.
     */
    public CustomizationNicSetting withMacAddress(String macAddress) {
        this.macAddress = macAddress;
        return this;
    }

}
