/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.vmwarecloudsimple.v2019_04_01;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Windows Identity. User data customization.
 */
public class CustomizationIdentityUserData {
    /**
     * Is password predefined in customization policy.
     */
    @JsonProperty(value = "isPasswordPredefined")
    private Boolean isPasswordPredefined;

    /**
     * Get is password predefined in customization policy.
     *
     * @return the isPasswordPredefined value
     */
    public Boolean isPasswordPredefined() {
        return this.isPasswordPredefined;
    }

    /**
     * Set is password predefined in customization policy.
     *
     * @param isPasswordPredefined the isPasswordPredefined value to set
     * @return the CustomizationIdentityUserData object itself.
     */
    public CustomizationIdentityUserData withIsPasswordPredefined(Boolean isPasswordPredefined) {
        this.isPasswordPredefined = isPasswordPredefined;
        return this;
    }

}
