/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.vmwarecloudsimple.v2019_04_01;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The CustomizationIPAddress model.
 */
public class CustomizationIPAddress {
    /**
     * Argument when Custom ip type is selected.
     */
    @JsonProperty(value = "argument")
    private String argument;

    /**
     * Defined Ip Address when Fixed ip type is selected.
     */
    @JsonProperty(value = "ipAddress")
    private String ipAddress;

    /**
     * Customization Specification ip type. Possible values include: 'CUSTOM',
     * 'DHCP_IP', 'FIXED_IP', 'USER_DEFINED'.
     */
    @JsonProperty(value = "type")
    private String type;

    /**
     * Get argument when Custom ip type is selected.
     *
     * @return the argument value
     */
    public String argument() {
        return this.argument;
    }

    /**
     * Set argument when Custom ip type is selected.
     *
     * @param argument the argument value to set
     * @return the CustomizationIPAddress object itself.
     */
    public CustomizationIPAddress withArgument(String argument) {
        this.argument = argument;
        return this;
    }

    /**
     * Get defined Ip Address when Fixed ip type is selected.
     *
     * @return the ipAddress value
     */
    public String ipAddress() {
        return this.ipAddress;
    }

    /**
     * Set defined Ip Address when Fixed ip type is selected.
     *
     * @param ipAddress the ipAddress value to set
     * @return the CustomizationIPAddress object itself.
     */
    public CustomizationIPAddress withIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
        return this;
    }

    /**
     * Get customization Specification ip type. Possible values include: 'CUSTOM', 'DHCP_IP', 'FIXED_IP', 'USER_DEFINED'.
     *
     * @return the type value
     */
    public String type() {
        return this.type;
    }

    /**
     * Set customization Specification ip type. Possible values include: 'CUSTOM', 'DHCP_IP', 'FIXED_IP', 'USER_DEFINED'.
     *
     * @param type the type value to set
     * @return the CustomizationIPAddress object itself.
     */
    public CustomizationIPAddress withType(String type) {
        this.type = type;
        return this;
    }

}
