/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.vmwarecloudsimple.v2019_04_01;

import com.microsoft.azure.arm.model.HasInner;
import com.microsoft.azure.management.vmwarecloudsimple.v2019_04_01.implementation.CustomizationPolicyInner;
import com.microsoft.azure.arm.model.Indexable;
import com.microsoft.azure.arm.model.Refreshable;
import com.microsoft.azure.arm.resources.models.HasManager;
import com.microsoft.azure.management.vmwarecloudsimple.v2019_04_01.implementation.VMwareCloudSimpleManager;

/**
 * Type representing CustomizationPolicy.
 */
public interface CustomizationPolicy extends HasInner<CustomizationPolicyInner>, Indexable, Refreshable<CustomizationPolicy>, HasManager<VMwareCloudSimpleManager> {
    /**
     * @return the customizationPolicyPropertiesType value.
     */
    String customizationPolicyPropertiesType();

    /**
     * @return the description value.
     */
    String description();

    /**
     * @return the id value.
     */
    String id();

    /**
     * @return the location value.
     */
    String location();

    /**
     * @return the name value.
     */
    String name();

    /**
     * @return the privateCloudId value.
     */
    String privateCloudId();

    /**
     * @return the specification value.
     */
    CustomizationSpecification specification();

    /**
     * @return the type value.
     */
    String type();

    /**
     * @return the version value.
     */
    String version();

}
