/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.vmwarecloudsimple.v2019_04_01;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Host name model.
 */
public class CustomizationHostName {
    /**
     * Hostname.
     */
    @JsonProperty(value = "name")
    private String name;

    /**
     * Type of host name. Possible values include: 'USER_DEFINED',
     * 'PREFIX_BASED', 'FIXED', 'VIRTUAL_MACHINE_NAME', 'CUSTOM_NAME'.
     */
    @JsonProperty(value = "type")
    private String type;

    /**
     * Get hostname.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set hostname.
     *
     * @param name the name value to set
     * @return the CustomizationHostName object itself.
     */
    public CustomizationHostName withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get type of host name. Possible values include: 'USER_DEFINED', 'PREFIX_BASED', 'FIXED', 'VIRTUAL_MACHINE_NAME', 'CUSTOM_NAME'.
     *
     * @return the type value
     */
    public String type() {
        return this.type;
    }

    /**
     * Set type of host name. Possible values include: 'USER_DEFINED', 'PREFIX_BASED', 'FIXED', 'VIRTUAL_MACHINE_NAME', 'CUSTOM_NAME'.
     *
     * @param type the type value to set
     * @return the CustomizationHostName object itself.
     */
    public CustomizationHostName withType(String type) {
        this.type = type;
        return this;
    }

}
