/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.vmwarecloudsimple.v2019_04_01;

import rx.Observable;
import com.microsoft.azure.management.vmwarecloudsimple.v2019_04_01.implementation.CustomizationPoliciesInner;
import com.microsoft.azure.arm.model.HasInner;

/**
 * Type representing CustomizationPolicies.
 */
public interface CustomizationPolicies extends HasInner<CustomizationPoliciesInner> {
    /**
     * Implements get of customization policy.
     * Returns customization policy by its name.
     *
     * @param regionId The region Id (westus, eastus)
     * @param pcName The private cloud name
     * @param customizationPolicyName customization policy name
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable for the request
     */
    Observable<CustomizationPolicy> getAsync(String regionId, String pcName, String customizationPolicyName);

    /**
     * Implements get of customization policies list.
     * Returns list of customization policies in region for private cloud.
     *
     * @param regionId The region Id (westus, eastus)
     * @param pcName The private cloud name
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable for the request
     */
    Observable<CustomizationPolicy> listAsync(final String regionId, final String pcName);

}
