/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.vmwarecloudsimple.v2019_04_01;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The CustomizationIdentity model.
 */
public class CustomizationIdentity {
    /**
     * Windows Text Identity. Prepared data.
     */
    @JsonProperty(value = "data")
    private String data;

    /**
     * Virtual machine host name settings.
     */
    @JsonProperty(value = "hostName")
    private CustomizationHostName hostName;

    /**
     * Identity type. Possible values include: 'WINDOWS_TEXT', 'WINDOWS',
     * 'LINUX'.
     */
    @JsonProperty(value = "type")
    private String type;

    /**
     * Windows Identity. User data customization.
     */
    @JsonProperty(value = "userData")
    private CustomizationIdentityUserData userData;

    /**
     * Get windows Text Identity. Prepared data.
     *
     * @return the data value
     */
    public String data() {
        return this.data;
    }

    /**
     * Set windows Text Identity. Prepared data.
     *
     * @param data the data value to set
     * @return the CustomizationIdentity object itself.
     */
    public CustomizationIdentity withData(String data) {
        this.data = data;
        return this;
    }

    /**
     * Get virtual machine host name settings.
     *
     * @return the hostName value
     */
    public CustomizationHostName hostName() {
        return this.hostName;
    }

    /**
     * Set virtual machine host name settings.
     *
     * @param hostName the hostName value to set
     * @return the CustomizationIdentity object itself.
     */
    public CustomizationIdentity withHostName(CustomizationHostName hostName) {
        this.hostName = hostName;
        return this;
    }

    /**
     * Get identity type. Possible values include: 'WINDOWS_TEXT', 'WINDOWS', 'LINUX'.
     *
     * @return the type value
     */
    public String type() {
        return this.type;
    }

    /**
     * Set identity type. Possible values include: 'WINDOWS_TEXT', 'WINDOWS', 'LINUX'.
     *
     * @param type the type value to set
     * @return the CustomizationIdentity object itself.
     */
    public CustomizationIdentity withType(String type) {
        this.type = type;
        return this;
    }

    /**
     * Get windows Identity. User data customization.
     *
     * @return the userData value
     */
    public CustomizationIdentityUserData userData() {
        return this.userData;
    }

    /**
     * Set windows Identity. User data customization.
     *
     * @param userData the userData value to set
     * @return the CustomizationIdentity object itself.
     */
    public CustomizationIdentity withUserData(CustomizationIdentityUserData userData) {
        this.userData = userData;
        return this;
    }

}
