/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.vmwarecloudsimple.v2019_04_01;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The specification for Customization Policy.
 */
public class CustomizationSpecification {
    /**
     * Customization Identity. It contains data about user and hostname.
     */
    @JsonProperty(value = "identity")
    private CustomizationIdentity identity;

    /**
     * Network interface settings.
     */
    @JsonProperty(value = "nicSettings")
    private List<CustomizationNicSetting> nicSettings;

    /**
     * Get customization Identity. It contains data about user and hostname.
     *
     * @return the identity value
     */
    public CustomizationIdentity identity() {
        return this.identity;
    }

    /**
     * Set customization Identity. It contains data about user and hostname.
     *
     * @param identity the identity value to set
     * @return the CustomizationSpecification object itself.
     */
    public CustomizationSpecification withIdentity(CustomizationIdentity identity) {
        this.identity = identity;
        return this;
    }

    /**
     * Get network interface settings.
     *
     * @return the nicSettings value
     */
    public List<CustomizationNicSetting> nicSettings() {
        return this.nicSettings;
    }

    /**
     * Set network interface settings.
     *
     * @param nicSettings the nicSettings value to set
     * @return the CustomizationSpecification object itself.
     */
    public CustomizationSpecification withNicSettings(List<CustomizationNicSetting> nicSettings) {
        this.nicSettings = nicSettings;
        return this;
    }

}
