/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.vmwarecloudsimple.v2019_04_01;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Guest OS nic customization.
 */
public class GuestOSNICCustomization {
    /**
     * IP address allocation method. Possible values include: 'static',
     * 'dynamic'.
     */
    @JsonProperty(value = "allocation")
    private String allocation;

    /**
     * List of dns servers to use.
     */
    @JsonProperty(value = "dnsServers")
    private List<String> dnsServers;

    /**
     * Gateway addresses assigned to nic.
     */
    @JsonProperty(value = "gateway")
    private List<String> gateway;

    /**
     * Static ip address for nic.
     */
    @JsonProperty(value = "ipAddress")
    private String ipAddress;

    /**
     * Network mask for nic.
     */
    @JsonProperty(value = "mask")
    private String mask;

    /**
     * primary WINS server for Windows.
     */
    @JsonProperty(value = "primaryWinsServer")
    private String primaryWinsServer;

    /**
     * secondary WINS server for Windows.
     */
    @JsonProperty(value = "secondaryWinsServer")
    private String secondaryWinsServer;

    /**
     * Get iP address allocation method. Possible values include: 'static', 'dynamic'.
     *
     * @return the allocation value
     */
    public String allocation() {
        return this.allocation;
    }

    /**
     * Set iP address allocation method. Possible values include: 'static', 'dynamic'.
     *
     * @param allocation the allocation value to set
     * @return the GuestOSNICCustomization object itself.
     */
    public GuestOSNICCustomization withAllocation(String allocation) {
        this.allocation = allocation;
        return this;
    }

    /**
     * Get list of dns servers to use.
     *
     * @return the dnsServers value
     */
    public List<String> dnsServers() {
        return this.dnsServers;
    }

    /**
     * Set list of dns servers to use.
     *
     * @param dnsServers the dnsServers value to set
     * @return the GuestOSNICCustomization object itself.
     */
    public GuestOSNICCustomization withDnsServers(List<String> dnsServers) {
        this.dnsServers = dnsServers;
        return this;
    }

    /**
     * Get gateway addresses assigned to nic.
     *
     * @return the gateway value
     */
    public List<String> gateway() {
        return this.gateway;
    }

    /**
     * Set gateway addresses assigned to nic.
     *
     * @param gateway the gateway value to set
     * @return the GuestOSNICCustomization object itself.
     */
    public GuestOSNICCustomization withGateway(List<String> gateway) {
        this.gateway = gateway;
        return this;
    }

    /**
     * Get static ip address for nic.
     *
     * @return the ipAddress value
     */
    public String ipAddress() {
        return this.ipAddress;
    }

    /**
     * Set static ip address for nic.
     *
     * @param ipAddress the ipAddress value to set
     * @return the GuestOSNICCustomization object itself.
     */
    public GuestOSNICCustomization withIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
        return this;
    }

    /**
     * Get network mask for nic.
     *
     * @return the mask value
     */
    public String mask() {
        return this.mask;
    }

    /**
     * Set network mask for nic.
     *
     * @param mask the mask value to set
     * @return the GuestOSNICCustomization object itself.
     */
    public GuestOSNICCustomization withMask(String mask) {
        this.mask = mask;
        return this;
    }

    /**
     * Get primary WINS server for Windows.
     *
     * @return the primaryWinsServer value
     */
    public String primaryWinsServer() {
        return this.primaryWinsServer;
    }

    /**
     * Set primary WINS server for Windows.
     *
     * @param primaryWinsServer the primaryWinsServer value to set
     * @return the GuestOSNICCustomization object itself.
     */
    public GuestOSNICCustomization withPrimaryWinsServer(String primaryWinsServer) {
        this.primaryWinsServer = primaryWinsServer;
        return this;
    }

    /**
     * Get secondary WINS server for Windows.
     *
     * @return the secondaryWinsServer value
     */
    public String secondaryWinsServer() {
        return this.secondaryWinsServer;
    }

    /**
     * Set secondary WINS server for Windows.
     *
     * @param secondaryWinsServer the secondaryWinsServer value to set
     * @return the GuestOSNICCustomization object itself.
     */
    public GuestOSNICCustomization withSecondaryWinsServer(String secondaryWinsServer) {
        this.secondaryWinsServer = secondaryWinsServer;
        return this;
    }

}
