/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.vmwarecloudsimple.v2019_04_01;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Guest OS Customization properties.
 */
public class GuestOSCustomization {
    /**
     * List of dns servers to use.
     */
    @JsonProperty(value = "dnsServers")
    private List<String> dnsServers;

    /**
     * Virtual Machine hostname.
     */
    @JsonProperty(value = "hostName")
    private String hostName;

    /**
     * Password for login.
     */
    @JsonProperty(value = "password")
    private String password;

    /**
     * id of customization policy.
     */
    @JsonProperty(value = "policyId")
    private String policyId;

    /**
     * Username for login.
     */
    @JsonProperty(value = "username")
    private String username;

    /**
     * Get list of dns servers to use.
     *
     * @return the dnsServers value
     */
    public List<String> dnsServers() {
        return this.dnsServers;
    }

    /**
     * Set list of dns servers to use.
     *
     * @param dnsServers the dnsServers value to set
     * @return the GuestOSCustomization object itself.
     */
    public GuestOSCustomization withDnsServers(List<String> dnsServers) {
        this.dnsServers = dnsServers;
        return this;
    }

    /**
     * Get virtual Machine hostname.
     *
     * @return the hostName value
     */
    public String hostName() {
        return this.hostName;
    }

    /**
     * Set virtual Machine hostname.
     *
     * @param hostName the hostName value to set
     * @return the GuestOSCustomization object itself.
     */
    public GuestOSCustomization withHostName(String hostName) {
        this.hostName = hostName;
        return this;
    }

    /**
     * Get password for login.
     *
     * @return the password value
     */
    public String password() {
        return this.password;
    }

    /**
     * Set password for login.
     *
     * @param password the password value to set
     * @return the GuestOSCustomization object itself.
     */
    public GuestOSCustomization withPassword(String password) {
        this.password = password;
        return this;
    }

    /**
     * Get id of customization policy.
     *
     * @return the policyId value
     */
    public String policyId() {
        return this.policyId;
    }

    /**
     * Set id of customization policy.
     *
     * @param policyId the policyId value to set
     * @return the GuestOSCustomization object itself.
     */
    public GuestOSCustomization withPolicyId(String policyId) {
        this.policyId = policyId;
        return this;
    }

    /**
     * Get username for login.
     *
     * @return the username value
     */
    public String username() {
        return this.username;
    }

    /**
     * Set username for login.
     *
     * @param username the username value to set
     * @return the GuestOSCustomization object itself.
     */
    public GuestOSCustomization withUsername(String username) {
        this.username = username;
        return this;
    }

}
