/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.billing.v2019_10_01_preview;

import com.microsoft.azure.arm.model.HasInner;
import com.microsoft.azure.management.billing.v2019_10_01_preview.implementation.InvoiceSectionInner;
import com.microsoft.azure.arm.model.Indexable;
import com.microsoft.azure.arm.model.Refreshable;
import com.microsoft.azure.arm.model.Updatable;
import com.microsoft.azure.arm.model.Appliable;
import com.microsoft.azure.arm.resources.models.HasManager;
import com.microsoft.azure.management.billing.v2019_10_01_preview.implementation.BillingManager;

/**
 * Type representing InvoiceSection.
 */
public interface InvoiceSection extends HasInner<InvoiceSectionInner>, Indexable, Refreshable<InvoiceSection>, Updatable<InvoiceSection.Update>, HasManager<BillingManager> {
    /**
     * @return the displayName value.
     */
    String displayName();

    /**
     * @return the id value.
     */
    String id();

    /**
     * @return the name value.
     */
    String name();

    /**
     * @return the type value.
     */
    String type();

    /**
     * The template for a InvoiceSection update operation, containing all the settings that can be modified.
     */
    interface Update extends Appliable<InvoiceSection>, UpdateStages.WithDisplayName {
    }

    /**
     * Grouping of InvoiceSection update stages.
     */
    interface UpdateStages {
        /**
         * The stage of the invoicesection update allowing to specify DisplayName.
         */
        interface WithDisplayName {
            /**
             * Specifies displayName.
             * @param displayName The name of the InvoiceSection
             * @return the next update stage
             */
            Update withDisplayName(String displayName);
        }

    }
}
