/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.billing.v2019_10_01_preview;

import rx.Observable;
import com.microsoft.azure.management.billing.v2019_10_01_preview.implementation.PartnerTransfersTransfersInner;
import com.microsoft.azure.arm.model.HasInner;

/**
 * Type representing PartnerTransfersTransfers.
 */
public interface PartnerTransfersTransfers extends HasInner<PartnerTransfersTransfersInner> {
    /**
     * Lists all transfer's details initiated from given invoice section.
     *
     * @param billingAccountName billing Account Id.
     * @param billingProfileName Billing Profile Id.
     * @param customerName Customer name.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable for the request
     */
    Observable<CustomerBillingProfileBillingAccountTransferDetailsModel> listAsync(final String billingAccountName, final String billingProfileName, final String customerName);

}
