/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.policy.v2019_09_01;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The policy definition reference.
 */
public class PolicyDefinitionReference {
    /**
     * The ID of the policy definition or policy set definition.
     */
    @JsonProperty(value = "policyDefinitionId", required = true)
    private String policyDefinitionId;

    /**
     * Required if a parameter is used in policy rule.
     */
    @JsonProperty(value = "parameters")
    private Object parameters;

    /**
     * A unique id (within the policy set definition) for this policy
     * definition reference.
     */
    @JsonProperty(value = "policyDefinitionReferenceId")
    private String policyDefinitionReferenceId;

    /**
     * The name of the groups that this policy definition reference belongs to.
     */
    @JsonProperty(value = "groupNames")
    private List<String> groupNames;

    /**
     * Get the ID of the policy definition or policy set definition.
     *
     * @return the policyDefinitionId value
     */
    public String policyDefinitionId() {
        return this.policyDefinitionId;
    }

    /**
     * Set the ID of the policy definition or policy set definition.
     *
     * @param policyDefinitionId the policyDefinitionId value to set
     * @return the PolicyDefinitionReference object itself.
     */
    public PolicyDefinitionReference withPolicyDefinitionId(String policyDefinitionId) {
        this.policyDefinitionId = policyDefinitionId;
        return this;
    }

    /**
     * Get required if a parameter is used in policy rule.
     *
     * @return the parameters value
     */
    public Object parameters() {
        return this.parameters;
    }

    /**
     * Set required if a parameter is used in policy rule.
     *
     * @param parameters the parameters value to set
     * @return the PolicyDefinitionReference object itself.
     */
    public PolicyDefinitionReference withParameters(Object parameters) {
        this.parameters = parameters;
        return this;
    }

    /**
     * Get a unique id (within the policy set definition) for this policy definition reference.
     *
     * @return the policyDefinitionReferenceId value
     */
    public String policyDefinitionReferenceId() {
        return this.policyDefinitionReferenceId;
    }

    /**
     * Set a unique id (within the policy set definition) for this policy definition reference.
     *
     * @param policyDefinitionReferenceId the policyDefinitionReferenceId value to set
     * @return the PolicyDefinitionReference object itself.
     */
    public PolicyDefinitionReference withPolicyDefinitionReferenceId(String policyDefinitionReferenceId) {
        this.policyDefinitionReferenceId = policyDefinitionReferenceId;
        return this;
    }

    /**
     * Get the name of the groups that this policy definition reference belongs to.
     *
     * @return the groupNames value
     */
    public List<String> groupNames() {
        return this.groupNames;
    }

    /**
     * Set the name of the groups that this policy definition reference belongs to.
     *
     * @param groupNames the groupNames value to set
     * @return the PolicyDefinitionReference object itself.
     */
    public PolicyDefinitionReference withGroupNames(List<String> groupNames) {
        this.groupNames = groupNames;
        return this;
    }

}
