/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.vmwarecloudsimple.v2019_04_01.implementation;

import com.microsoft.azure.management.vmwarecloudsimple.v2019_04_01.CustomizationSpecification;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.microsoft.rest.serializer.JsonFlatten;

/**
 * The virtual machine customization policy.
 */
@JsonFlatten
public class CustomizationPolicyInner {
    /**
     * Customization policy azure id.
     */
    @JsonProperty(value = "id")
    private String id;

    /**
     * Azure region.
     */
    @JsonProperty(value = "location")
    private String location;

    /**
     * Customization policy name.
     */
    @JsonProperty(value = "name", access = JsonProperty.Access.WRITE_ONLY)
    private String name;

    /**
     * Policy description.
     */
    @JsonProperty(value = "properties.description")
    private String description;

    /**
     * The Private cloud id.
     */
    @JsonProperty(value = "properties.privateCloudId")
    private String privateCloudId;

    /**
     * Detailed customization policy specification.
     */
    @JsonProperty(value = "properties.specification")
    private CustomizationSpecification specification;

    /**
     * The type of customization (Linux or Windows). Possible values include:
     * 'LINUX', 'WINDOWS'.
     */
    @JsonProperty(value = "properties.type")
    private String customizationPolicyPropertiesType;

    /**
     * Policy version.
     */
    @JsonProperty(value = "properties.version")
    private String version;

    /**
     * The type property.
     */
    @JsonProperty(value = "type", access = JsonProperty.Access.WRITE_ONLY)
    private String type;

    /**
     * Get customization policy azure id.
     *
     * @return the id value
     */
    public String id() {
        return this.id;
    }

    /**
     * Set customization policy azure id.
     *
     * @param id the id value to set
     * @return the CustomizationPolicyInner object itself.
     */
    public CustomizationPolicyInner withId(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get azure region.
     *
     * @return the location value
     */
    public String location() {
        return this.location;
    }

    /**
     * Set azure region.
     *
     * @param location the location value to set
     * @return the CustomizationPolicyInner object itself.
     */
    public CustomizationPolicyInner withLocation(String location) {
        this.location = location;
        return this;
    }

    /**
     * Get customization policy name.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Get policy description.
     *
     * @return the description value
     */
    public String description() {
        return this.description;
    }

    /**
     * Set policy description.
     *
     * @param description the description value to set
     * @return the CustomizationPolicyInner object itself.
     */
    public CustomizationPolicyInner withDescription(String description) {
        this.description = description;
        return this;
    }

    /**
     * Get the Private cloud id.
     *
     * @return the privateCloudId value
     */
    public String privateCloudId() {
        return this.privateCloudId;
    }

    /**
     * Set the Private cloud id.
     *
     * @param privateCloudId the privateCloudId value to set
     * @return the CustomizationPolicyInner object itself.
     */
    public CustomizationPolicyInner withPrivateCloudId(String privateCloudId) {
        this.privateCloudId = privateCloudId;
        return this;
    }

    /**
     * Get detailed customization policy specification.
     *
     * @return the specification value
     */
    public CustomizationSpecification specification() {
        return this.specification;
    }

    /**
     * Set detailed customization policy specification.
     *
     * @param specification the specification value to set
     * @return the CustomizationPolicyInner object itself.
     */
    public CustomizationPolicyInner withSpecification(CustomizationSpecification specification) {
        this.specification = specification;
        return this;
    }

    /**
     * Get the type of customization (Linux or Windows). Possible values include: 'LINUX', 'WINDOWS'.
     *
     * @return the customizationPolicyPropertiesType value
     */
    public String customizationPolicyPropertiesType() {
        return this.customizationPolicyPropertiesType;
    }

    /**
     * Set the type of customization (Linux or Windows). Possible values include: 'LINUX', 'WINDOWS'.
     *
     * @param customizationPolicyPropertiesType the customizationPolicyPropertiesType value to set
     * @return the CustomizationPolicyInner object itself.
     */
    public CustomizationPolicyInner withCustomizationPolicyPropertiesType(String customizationPolicyPropertiesType) {
        this.customizationPolicyPropertiesType = customizationPolicyPropertiesType;
        return this;
    }

    /**
     * Get policy version.
     *
     * @return the version value
     */
    public String version() {
        return this.version;
    }

    /**
     * Set policy version.
     *
     * @param version the version value to set
     * @return the CustomizationPolicyInner object itself.
     */
    public CustomizationPolicyInner withVersion(String version) {
        this.version = version;
        return this;
    }

    /**
     * Get the type value.
     *
     * @return the type value
     */
    public String type() {
        return this.type;
    }

}
