/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.vmwarecloudsimple.v2019_04_01.implementation;

import retrofit2.Retrofit;
import com.google.common.reflect.TypeToken;
import com.microsoft.azure.AzureServiceFuture;
import com.microsoft.azure.ListOperationCallback;
import com.microsoft.azure.management.vmwarecloudsimple.v2019_04_01.CSRPErrorException;
import com.microsoft.azure.Page;
import com.microsoft.azure.PagedList;
import com.microsoft.rest.ServiceCallback;
import com.microsoft.rest.ServiceFuture;
import com.microsoft.rest.ServiceResponse;
import java.io.IOException;
import java.util.List;
import okhttp3.ResponseBody;
import retrofit2.http.GET;
import retrofit2.http.Header;
import retrofit2.http.Headers;
import retrofit2.http.Path;
import retrofit2.http.Query;
import retrofit2.http.Url;
import retrofit2.Response;
import rx.functions.Func1;
import rx.Observable;

/**
 * An instance of this class provides access to all the operations defined
 * in CustomizationPolicies.
 */
public class CustomizationPoliciesInner {
    /** The Retrofit service to perform REST calls. */
    private CustomizationPoliciesService service;
    /** The service client containing this operation class. */
    private VMwareCloudSimpleClientImpl client;

    /**
     * Initializes an instance of CustomizationPoliciesInner.
     *
     * @param retrofit the Retrofit instance built from a Retrofit Builder.
     * @param client the instance of the service client containing this operation class.
     */
    public CustomizationPoliciesInner(Retrofit retrofit, VMwareCloudSimpleClientImpl client) {
        this.service = retrofit.create(CustomizationPoliciesService.class);
        this.client = client;
    }

    /**
     * The interface defining all the services for CustomizationPolicies to be
     * used by Retrofit to perform actually REST calls.
     */
    interface CustomizationPoliciesService {
        @Headers({ "Content-Type: application/json; charset=utf-8", "x-ms-logging-context: com.microsoft.azure.management.vmwarecloudsimple.v2019_04_01.CustomizationPolicies list" })
        @GET("subscriptions/{subscriptionId}/providers/Microsoft.VMwareCloudSimple/locations/{regionId}/privateClouds/{pcName}/customizationPolicies")
        Observable<Response<ResponseBody>> list(@Path("subscriptionId") String subscriptionId, @Path("regionId") String regionId, @Path("pcName") String pcName, @Query("api-version") String apiVersion, @Query("$filter") String filter, @Header("accept-language") String acceptLanguage, @Header("User-Agent") String userAgent);

        @Headers({ "Content-Type: application/json; charset=utf-8", "x-ms-logging-context: com.microsoft.azure.management.vmwarecloudsimple.v2019_04_01.CustomizationPolicies get" })
        @GET("subscriptions/{subscriptionId}/providers/Microsoft.VMwareCloudSimple/locations/{regionId}/privateClouds/{pcName}/customizationPolicies/{customizationPolicyName}")
        Observable<Response<ResponseBody>> get(@Path("subscriptionId") String subscriptionId, @Path("regionId") String regionId, @Path("pcName") String pcName, @Path("customizationPolicyName") String customizationPolicyName, @Query("api-version") String apiVersion, @Header("accept-language") String acceptLanguage, @Header("User-Agent") String userAgent);

        @Headers({ "Content-Type: application/json; charset=utf-8", "x-ms-logging-context: com.microsoft.azure.management.vmwarecloudsimple.v2019_04_01.CustomizationPolicies listNext" })
        @GET
        Observable<Response<ResponseBody>> listNext(@Url String nextUrl, @Header("accept-language") String acceptLanguage, @Header("User-Agent") String userAgent);

    }

    /**
     * Implements get of customization policies list.
     * Returns list of customization policies in region for private cloud.
     *
     * @param regionId The region Id (westus, eastus)
     * @param pcName The private cloud name
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @throws CSRPErrorException thrown if the request is rejected by server
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent
     * @return the PagedList&lt;CustomizationPolicyInner&gt; object if successful.
     */
    public PagedList<CustomizationPolicyInner> list(final String regionId, final String pcName) {
        ServiceResponse<Page<CustomizationPolicyInner>> response = listSinglePageAsync(regionId, pcName).toBlocking().single();
        return new PagedList<CustomizationPolicyInner>(response.body()) {
            @Override
            public Page<CustomizationPolicyInner> nextPage(String nextPageLink) {
                return listNextSinglePageAsync(nextPageLink).toBlocking().single().body();
            }
        };
    }

    /**
     * Implements get of customization policies list.
     * Returns list of customization policies in region for private cloud.
     *
     * @param regionId The region Id (westus, eastus)
     * @param pcName The private cloud name
     * @param serviceCallback the async ServiceCallback to handle successful and failed responses.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the {@link ServiceFuture} object
     */
    public ServiceFuture<List<CustomizationPolicyInner>> listAsync(final String regionId, final String pcName, final ListOperationCallback<CustomizationPolicyInner> serviceCallback) {
        return AzureServiceFuture.fromPageResponse(
            listSinglePageAsync(regionId, pcName),
            new Func1<String, Observable<ServiceResponse<Page<CustomizationPolicyInner>>>>() {
                @Override
                public Observable<ServiceResponse<Page<CustomizationPolicyInner>>> call(String nextPageLink) {
                    return listNextSinglePageAsync(nextPageLink);
                }
            },
            serviceCallback);
    }

    /**
     * Implements get of customization policies list.
     * Returns list of customization policies in region for private cloud.
     *
     * @param regionId The region Id (westus, eastus)
     * @param pcName The private cloud name
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the PagedList&lt;CustomizationPolicyInner&gt; object
     */
    public Observable<Page<CustomizationPolicyInner>> listAsync(final String regionId, final String pcName) {
        return listWithServiceResponseAsync(regionId, pcName)
            .map(new Func1<ServiceResponse<Page<CustomizationPolicyInner>>, Page<CustomizationPolicyInner>>() {
                @Override
                public Page<CustomizationPolicyInner> call(ServiceResponse<Page<CustomizationPolicyInner>> response) {
                    return response.body();
                }
            });
    }

    /**
     * Implements get of customization policies list.
     * Returns list of customization policies in region for private cloud.
     *
     * @param regionId The region Id (westus, eastus)
     * @param pcName The private cloud name
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the PagedList&lt;CustomizationPolicyInner&gt; object
     */
    public Observable<ServiceResponse<Page<CustomizationPolicyInner>>> listWithServiceResponseAsync(final String regionId, final String pcName) {
        return listSinglePageAsync(regionId, pcName)
            .concatMap(new Func1<ServiceResponse<Page<CustomizationPolicyInner>>, Observable<ServiceResponse<Page<CustomizationPolicyInner>>>>() {
                @Override
                public Observable<ServiceResponse<Page<CustomizationPolicyInner>>> call(ServiceResponse<Page<CustomizationPolicyInner>> page) {
                    String nextPageLink = page.body().nextPageLink();
                    if (nextPageLink == null) {
                        return Observable.just(page);
                    }
                    return Observable.just(page).concatWith(listNextWithServiceResponseAsync(nextPageLink));
                }
            });
    }

    /**
     * Implements get of customization policies list.
     * Returns list of customization policies in region for private cloud.
     *
     * @param regionId The region Id (westus, eastus)
     * @param pcName The private cloud name
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the PagedList&lt;CustomizationPolicyInner&gt; object wrapped in {@link ServiceResponse} if successful.
     */
    public Observable<ServiceResponse<Page<CustomizationPolicyInner>>> listSinglePageAsync(final String regionId, final String pcName) {
        if (this.client.subscriptionId() == null) {
            throw new IllegalArgumentException("Parameter this.client.subscriptionId() is required and cannot be null.");
        }
        if (regionId == null) {
            throw new IllegalArgumentException("Parameter regionId is required and cannot be null.");
        }
        if (pcName == null) {
            throw new IllegalArgumentException("Parameter pcName is required and cannot be null.");
        }
        if (this.client.apiVersion() == null) {
            throw new IllegalArgumentException("Parameter this.client.apiVersion() is required and cannot be null.");
        }
        final String filter = null;
        return service.list(this.client.subscriptionId(), regionId, pcName, this.client.apiVersion(), filter, this.client.acceptLanguage(), this.client.userAgent())
            .flatMap(new Func1<Response<ResponseBody>, Observable<ServiceResponse<Page<CustomizationPolicyInner>>>>() {
                @Override
                public Observable<ServiceResponse<Page<CustomizationPolicyInner>>> call(Response<ResponseBody> response) {
                    try {
                        ServiceResponse<PageImpl<CustomizationPolicyInner>> result = listDelegate(response);
                        return Observable.just(new ServiceResponse<Page<CustomizationPolicyInner>>(result.body(), result.response()));
                    } catch (Throwable t) {
                        return Observable.error(t);
                    }
                }
            });
    }

    /**
     * Implements get of customization policies list.
     * Returns list of customization policies in region for private cloud.
     *
     * @param regionId The region Id (westus, eastus)
     * @param pcName The private cloud name
     * @param filter The filter to apply on the list operation. only type is allowed here as a filter e.g. $filter=type eq 'xxxx'
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @throws CSRPErrorException thrown if the request is rejected by server
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent
     * @return the PagedList&lt;CustomizationPolicyInner&gt; object if successful.
     */
    public PagedList<CustomizationPolicyInner> list(final String regionId, final String pcName, final String filter) {
        ServiceResponse<Page<CustomizationPolicyInner>> response = listSinglePageAsync(regionId, pcName, filter).toBlocking().single();
        return new PagedList<CustomizationPolicyInner>(response.body()) {
            @Override
            public Page<CustomizationPolicyInner> nextPage(String nextPageLink) {
                return listNextSinglePageAsync(nextPageLink).toBlocking().single().body();
            }
        };
    }

    /**
     * Implements get of customization policies list.
     * Returns list of customization policies in region for private cloud.
     *
     * @param regionId The region Id (westus, eastus)
     * @param pcName The private cloud name
     * @param filter The filter to apply on the list operation. only type is allowed here as a filter e.g. $filter=type eq 'xxxx'
     * @param serviceCallback the async ServiceCallback to handle successful and failed responses.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the {@link ServiceFuture} object
     */
    public ServiceFuture<List<CustomizationPolicyInner>> listAsync(final String regionId, final String pcName, final String filter, final ListOperationCallback<CustomizationPolicyInner> serviceCallback) {
        return AzureServiceFuture.fromPageResponse(
            listSinglePageAsync(regionId, pcName, filter),
            new Func1<String, Observable<ServiceResponse<Page<CustomizationPolicyInner>>>>() {
                @Override
                public Observable<ServiceResponse<Page<CustomizationPolicyInner>>> call(String nextPageLink) {
                    return listNextSinglePageAsync(nextPageLink);
                }
            },
            serviceCallback);
    }

    /**
     * Implements get of customization policies list.
     * Returns list of customization policies in region for private cloud.
     *
     * @param regionId The region Id (westus, eastus)
     * @param pcName The private cloud name
     * @param filter The filter to apply on the list operation. only type is allowed here as a filter e.g. $filter=type eq 'xxxx'
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the PagedList&lt;CustomizationPolicyInner&gt; object
     */
    public Observable<Page<CustomizationPolicyInner>> listAsync(final String regionId, final String pcName, final String filter) {
        return listWithServiceResponseAsync(regionId, pcName, filter)
            .map(new Func1<ServiceResponse<Page<CustomizationPolicyInner>>, Page<CustomizationPolicyInner>>() {
                @Override
                public Page<CustomizationPolicyInner> call(ServiceResponse<Page<CustomizationPolicyInner>> response) {
                    return response.body();
                }
            });
    }

    /**
     * Implements get of customization policies list.
     * Returns list of customization policies in region for private cloud.
     *
     * @param regionId The region Id (westus, eastus)
     * @param pcName The private cloud name
     * @param filter The filter to apply on the list operation. only type is allowed here as a filter e.g. $filter=type eq 'xxxx'
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the PagedList&lt;CustomizationPolicyInner&gt; object
     */
    public Observable<ServiceResponse<Page<CustomizationPolicyInner>>> listWithServiceResponseAsync(final String regionId, final String pcName, final String filter) {
        return listSinglePageAsync(regionId, pcName, filter)
            .concatMap(new Func1<ServiceResponse<Page<CustomizationPolicyInner>>, Observable<ServiceResponse<Page<CustomizationPolicyInner>>>>() {
                @Override
                public Observable<ServiceResponse<Page<CustomizationPolicyInner>>> call(ServiceResponse<Page<CustomizationPolicyInner>> page) {
                    String nextPageLink = page.body().nextPageLink();
                    if (nextPageLink == null) {
                        return Observable.just(page);
                    }
                    return Observable.just(page).concatWith(listNextWithServiceResponseAsync(nextPageLink));
                }
            });
    }

    /**
     * Implements get of customization policies list.
     * Returns list of customization policies in region for private cloud.
     *
    ServiceResponse<PageImpl<CustomizationPolicyInner>> * @param regionId The region Id (westus, eastus)
    ServiceResponse<PageImpl<CustomizationPolicyInner>> * @param pcName The private cloud name
    ServiceResponse<PageImpl<CustomizationPolicyInner>> * @param filter The filter to apply on the list operation. only type is allowed here as a filter e.g. $filter=type eq 'xxxx'
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the PagedList&lt;CustomizationPolicyInner&gt; object wrapped in {@link ServiceResponse} if successful.
     */
    public Observable<ServiceResponse<Page<CustomizationPolicyInner>>> listSinglePageAsync(final String regionId, final String pcName, final String filter) {
        if (this.client.subscriptionId() == null) {
            throw new IllegalArgumentException("Parameter this.client.subscriptionId() is required and cannot be null.");
        }
        if (regionId == null) {
            throw new IllegalArgumentException("Parameter regionId is required and cannot be null.");
        }
        if (pcName == null) {
            throw new IllegalArgumentException("Parameter pcName is required and cannot be null.");
        }
        if (this.client.apiVersion() == null) {
            throw new IllegalArgumentException("Parameter this.client.apiVersion() is required and cannot be null.");
        }
        return service.list(this.client.subscriptionId(), regionId, pcName, this.client.apiVersion(), filter, this.client.acceptLanguage(), this.client.userAgent())
            .flatMap(new Func1<Response<ResponseBody>, Observable<ServiceResponse<Page<CustomizationPolicyInner>>>>() {
                @Override
                public Observable<ServiceResponse<Page<CustomizationPolicyInner>>> call(Response<ResponseBody> response) {
                    try {
                        ServiceResponse<PageImpl<CustomizationPolicyInner>> result = listDelegate(response);
                        return Observable.just(new ServiceResponse<Page<CustomizationPolicyInner>>(result.body(), result.response()));
                    } catch (Throwable t) {
                        return Observable.error(t);
                    }
                }
            });
    }

    private ServiceResponse<PageImpl<CustomizationPolicyInner>> listDelegate(Response<ResponseBody> response) throws CSRPErrorException, IOException, IllegalArgumentException {
        return this.client.restClient().responseBuilderFactory().<PageImpl<CustomizationPolicyInner>, CSRPErrorException>newInstance(this.client.serializerAdapter())
                .register(200, new TypeToken<PageImpl<CustomizationPolicyInner>>() { }.getType())
                .registerError(CSRPErrorException.class)
                .build(response);
    }

    /**
     * Implements get of customization policy.
     * Returns customization policy by its name.
     *
     * @param regionId The region Id (westus, eastus)
     * @param pcName The private cloud name
     * @param customizationPolicyName customization policy name
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @throws CSRPErrorException thrown if the request is rejected by server
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent
     * @return the CustomizationPolicyInner object if successful.
     */
    public CustomizationPolicyInner get(String regionId, String pcName, String customizationPolicyName) {
        return getWithServiceResponseAsync(regionId, pcName, customizationPolicyName).toBlocking().single().body();
    }

    /**
     * Implements get of customization policy.
     * Returns customization policy by its name.
     *
     * @param regionId The region Id (westus, eastus)
     * @param pcName The private cloud name
     * @param customizationPolicyName customization policy name
     * @param serviceCallback the async ServiceCallback to handle successful and failed responses.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the {@link ServiceFuture} object
     */
    public ServiceFuture<CustomizationPolicyInner> getAsync(String regionId, String pcName, String customizationPolicyName, final ServiceCallback<CustomizationPolicyInner> serviceCallback) {
        return ServiceFuture.fromResponse(getWithServiceResponseAsync(regionId, pcName, customizationPolicyName), serviceCallback);
    }

    /**
     * Implements get of customization policy.
     * Returns customization policy by its name.
     *
     * @param regionId The region Id (westus, eastus)
     * @param pcName The private cloud name
     * @param customizationPolicyName customization policy name
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the CustomizationPolicyInner object
     */
    public Observable<CustomizationPolicyInner> getAsync(String regionId, String pcName, String customizationPolicyName) {
        return getWithServiceResponseAsync(regionId, pcName, customizationPolicyName).map(new Func1<ServiceResponse<CustomizationPolicyInner>, CustomizationPolicyInner>() {
            @Override
            public CustomizationPolicyInner call(ServiceResponse<CustomizationPolicyInner> response) {
                return response.body();
            }
        });
    }

    /**
     * Implements get of customization policy.
     * Returns customization policy by its name.
     *
     * @param regionId The region Id (westus, eastus)
     * @param pcName The private cloud name
     * @param customizationPolicyName customization policy name
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the CustomizationPolicyInner object
     */
    public Observable<ServiceResponse<CustomizationPolicyInner>> getWithServiceResponseAsync(String regionId, String pcName, String customizationPolicyName) {
        if (this.client.subscriptionId() == null) {
            throw new IllegalArgumentException("Parameter this.client.subscriptionId() is required and cannot be null.");
        }
        if (regionId == null) {
            throw new IllegalArgumentException("Parameter regionId is required and cannot be null.");
        }
        if (pcName == null) {
            throw new IllegalArgumentException("Parameter pcName is required and cannot be null.");
        }
        if (customizationPolicyName == null) {
            throw new IllegalArgumentException("Parameter customizationPolicyName is required and cannot be null.");
        }
        if (this.client.apiVersion() == null) {
            throw new IllegalArgumentException("Parameter this.client.apiVersion() is required and cannot be null.");
        }
        return service.get(this.client.subscriptionId(), regionId, pcName, customizationPolicyName, this.client.apiVersion(), this.client.acceptLanguage(), this.client.userAgent())
            .flatMap(new Func1<Response<ResponseBody>, Observable<ServiceResponse<CustomizationPolicyInner>>>() {
                @Override
                public Observable<ServiceResponse<CustomizationPolicyInner>> call(Response<ResponseBody> response) {
                    try {
                        ServiceResponse<CustomizationPolicyInner> clientResponse = getDelegate(response);
                        return Observable.just(clientResponse);
                    } catch (Throwable t) {
                        return Observable.error(t);
                    }
                }
            });
    }

    private ServiceResponse<CustomizationPolicyInner> getDelegate(Response<ResponseBody> response) throws CSRPErrorException, IOException, IllegalArgumentException {
        return this.client.restClient().responseBuilderFactory().<CustomizationPolicyInner, CSRPErrorException>newInstance(this.client.serializerAdapter())
                .register(200, new TypeToken<CustomizationPolicyInner>() { }.getType())
                .registerError(CSRPErrorException.class)
                .build(response);
    }

    /**
     * Implements get of customization policies list.
     * Returns list of customization policies in region for private cloud.
     *
     * @param nextPageLink The NextLink from the previous successful call to List operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @throws CSRPErrorException thrown if the request is rejected by server
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent
     * @return the PagedList&lt;CustomizationPolicyInner&gt; object if successful.
     */
    public PagedList<CustomizationPolicyInner> listNext(final String nextPageLink) {
        ServiceResponse<Page<CustomizationPolicyInner>> response = listNextSinglePageAsync(nextPageLink).toBlocking().single();
        return new PagedList<CustomizationPolicyInner>(response.body()) {
            @Override
            public Page<CustomizationPolicyInner> nextPage(String nextPageLink) {
                return listNextSinglePageAsync(nextPageLink).toBlocking().single().body();
            }
        };
    }

    /**
     * Implements get of customization policies list.
     * Returns list of customization policies in region for private cloud.
     *
     * @param nextPageLink The NextLink from the previous successful call to List operation.
     * @param serviceFuture the ServiceFuture object tracking the Retrofit calls
     * @param serviceCallback the async ServiceCallback to handle successful and failed responses.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the {@link ServiceFuture} object
     */
    public ServiceFuture<List<CustomizationPolicyInner>> listNextAsync(final String nextPageLink, final ServiceFuture<List<CustomizationPolicyInner>> serviceFuture, final ListOperationCallback<CustomizationPolicyInner> serviceCallback) {
        return AzureServiceFuture.fromPageResponse(
            listNextSinglePageAsync(nextPageLink),
            new Func1<String, Observable<ServiceResponse<Page<CustomizationPolicyInner>>>>() {
                @Override
                public Observable<ServiceResponse<Page<CustomizationPolicyInner>>> call(String nextPageLink) {
                    return listNextSinglePageAsync(nextPageLink);
                }
            },
            serviceCallback);
    }

    /**
     * Implements get of customization policies list.
     * Returns list of customization policies in region for private cloud.
     *
     * @param nextPageLink The NextLink from the previous successful call to List operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the PagedList&lt;CustomizationPolicyInner&gt; object
     */
    public Observable<Page<CustomizationPolicyInner>> listNextAsync(final String nextPageLink) {
        return listNextWithServiceResponseAsync(nextPageLink)
            .map(new Func1<ServiceResponse<Page<CustomizationPolicyInner>>, Page<CustomizationPolicyInner>>() {
                @Override
                public Page<CustomizationPolicyInner> call(ServiceResponse<Page<CustomizationPolicyInner>> response) {
                    return response.body();
                }
            });
    }

    /**
     * Implements get of customization policies list.
     * Returns list of customization policies in region for private cloud.
     *
     * @param nextPageLink The NextLink from the previous successful call to List operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the PagedList&lt;CustomizationPolicyInner&gt; object
     */
    public Observable<ServiceResponse<Page<CustomizationPolicyInner>>> listNextWithServiceResponseAsync(final String nextPageLink) {
        return listNextSinglePageAsync(nextPageLink)
            .concatMap(new Func1<ServiceResponse<Page<CustomizationPolicyInner>>, Observable<ServiceResponse<Page<CustomizationPolicyInner>>>>() {
                @Override
                public Observable<ServiceResponse<Page<CustomizationPolicyInner>>> call(ServiceResponse<Page<CustomizationPolicyInner>> page) {
                    String nextPageLink = page.body().nextPageLink();
                    if (nextPageLink == null) {
                        return Observable.just(page);
                    }
                    return Observable.just(page).concatWith(listNextWithServiceResponseAsync(nextPageLink));
                }
            });
    }

    /**
     * Implements get of customization policies list.
     * Returns list of customization policies in region for private cloud.
     *
    ServiceResponse<PageImpl<CustomizationPolicyInner>> * @param nextPageLink The NextLink from the previous successful call to List operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the PagedList&lt;CustomizationPolicyInner&gt; object wrapped in {@link ServiceResponse} if successful.
     */
    public Observable<ServiceResponse<Page<CustomizationPolicyInner>>> listNextSinglePageAsync(final String nextPageLink) {
        if (nextPageLink == null) {
            throw new IllegalArgumentException("Parameter nextPageLink is required and cannot be null.");
        }
        String nextUrl = String.format("%s", nextPageLink);
        return service.listNext(nextUrl, this.client.acceptLanguage(), this.client.userAgent())
            .flatMap(new Func1<Response<ResponseBody>, Observable<ServiceResponse<Page<CustomizationPolicyInner>>>>() {
                @Override
                public Observable<ServiceResponse<Page<CustomizationPolicyInner>>> call(Response<ResponseBody> response) {
                    try {
                        ServiceResponse<PageImpl<CustomizationPolicyInner>> result = listNextDelegate(response);
                        return Observable.just(new ServiceResponse<Page<CustomizationPolicyInner>>(result.body(), result.response()));
                    } catch (Throwable t) {
                        return Observable.error(t);
                    }
                }
            });
    }

    private ServiceResponse<PageImpl<CustomizationPolicyInner>> listNextDelegate(Response<ResponseBody> response) throws CSRPErrorException, IOException, IllegalArgumentException {
        return this.client.restClient().responseBuilderFactory().<PageImpl<CustomizationPolicyInner>, CSRPErrorException>newInstance(this.client.serializerAdapter())
                .register(200, new TypeToken<PageImpl<CustomizationPolicyInner>>() { }.getType())
                .registerError(CSRPErrorException.class)
                .build(response);
    }

}
