/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.vmwarecloudsimple.v2019_04_01.implementation;

import com.microsoft.azure.management.vmwarecloudsimple.v2019_04_01.CustomizationPolicy;
import com.microsoft.azure.arm.model.implementation.IndexableRefreshableWrapperImpl;
import rx.Observable;
import com.microsoft.azure.management.vmwarecloudsimple.v2019_04_01.CustomizationSpecification;

class CustomizationPolicyImpl extends IndexableRefreshableWrapperImpl<CustomizationPolicy, CustomizationPolicyInner> implements CustomizationPolicy {
    private final VMwareCloudSimpleManager manager;
    private String regionId;
    private String pcName;
    private String customizationPolicyName;

    CustomizationPolicyImpl(CustomizationPolicyInner inner,  VMwareCloudSimpleManager manager) {
        super(null, inner);
        this.manager = manager;
        // set resource ancestor and positional variables
        this.regionId = IdParsingUtils.getValueFromIdByName(inner.id(), "locations");
        this.pcName = IdParsingUtils.getValueFromIdByName(inner.id(), "privateClouds");
        this.customizationPolicyName = IdParsingUtils.getValueFromIdByName(inner.id(), "customizationPolicies");
    }

    @Override
    public VMwareCloudSimpleManager manager() {
        return this.manager;
    }

    @Override
    protected Observable<CustomizationPolicyInner> getInnerAsync() {
        CustomizationPoliciesInner client = this.manager().inner().customizationPolicies();
        return client.getAsync(this.regionId, this.pcName, this.customizationPolicyName);
    }



    @Override
    public String customizationPolicyPropertiesType() {
        return this.inner().customizationPolicyPropertiesType();
    }

    @Override
    public String description() {
        return this.inner().description();
    }

    @Override
    public String id() {
        return this.inner().id();
    }

    @Override
    public String location() {
        return this.inner().location();
    }

    @Override
    public String name() {
        return this.inner().name();
    }

    @Override
    public String privateCloudId() {
        return this.inner().privateCloudId();
    }

    @Override
    public CustomizationSpecification specification() {
        return this.inner().specification();
    }

    @Override
    public String type() {
        return this.inner().type();
    }

    @Override
    public String version() {
        return this.inner().version();
    }

}
