/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * abc
 */

package com.microsoft.azure.management.azurestack.v2017_06_01.implementation;

import com.microsoft.azure.arm.model.implementation.WrapperImpl;
import com.microsoft.azure.management.azurestack.v2017_06_01.GetProducts;
import rx.functions.Func1;
import rx.Observable;
import com.microsoft.azure.management.azurestack.v2017_06_01.ProductList;

class GetProductsImpl extends WrapperImpl<GetProductsInner> implements GetProducts {
    private final AzureStackManager manager;

    GetProductsImpl(AzureStackManager manager) {
        super(manager.inner().getProducts());
        this.manager = manager;
    }

    public AzureStackManager manager() {
        return this.manager;
    }

    @Override
    public Observable<ProductList> listAsync(String resourceGroup, String registrationName) {
        GetProductsInner client = this.inner();
        return client.listAsync(resourceGroup, registrationName)
        .map(new Func1<ProductListInner, ProductList>() {
            @Override
            public ProductList call(ProductListInner inner) {
                return new ProductListImpl(inner, manager());
            }
        });
    }

}
