/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.billing.v2019_10_01_preview.implementation;

import retrofit2.Retrofit;
import com.google.common.reflect.TypeToken;
import com.microsoft.azure.AzureServiceFuture;
import com.microsoft.azure.ListOperationCallback;
import com.microsoft.azure.management.billing.v2019_10_01_preview.ErrorResponseException;
import com.microsoft.azure.Page;
import com.microsoft.azure.PagedList;
import com.microsoft.rest.ServiceFuture;
import com.microsoft.rest.ServiceResponse;
import java.io.IOException;
import java.util.List;
import okhttp3.ResponseBody;
import retrofit2.http.GET;
import retrofit2.http.Header;
import retrofit2.http.Headers;
import retrofit2.http.Path;
import retrofit2.http.Url;
import retrofit2.Response;
import rx.functions.Func1;
import rx.Observable;

/**
 * An instance of this class provides access to all the operations defined
 * in PartnerTransfersTransfers.
 */
public class PartnerTransfersTransfersInner {
    /** The Retrofit service to perform REST calls. */
    private PartnerTransfersTransfersService service;
    /** The service client containing this operation class. */
    private BillingManagementClientImpl client;

    /**
     * Initializes an instance of PartnerTransfersTransfersInner.
     *
     * @param retrofit the Retrofit instance built from a Retrofit Builder.
     * @param client the instance of the service client containing this operation class.
     */
    public PartnerTransfersTransfersInner(Retrofit retrofit, BillingManagementClientImpl client) {
        this.service = retrofit.create(PartnerTransfersTransfersService.class);
        this.client = client;
    }

    /**
     * The interface defining all the services for PartnerTransfersTransfers to be
     * used by Retrofit to perform actually REST calls.
     */
    interface PartnerTransfersTransfersService {
        @Headers({ "Content-Type: application/json; charset=utf-8", "x-ms-logging-context: com.microsoft.azure.management.billing.v2019_10_01_preview.PartnerTransfersTransfers list" })
        @GET("providers/Microsoft.Billing/billingAccounts/{billingAccountName}/billingProfiles/{billingProfileName}/customers/{customerName}/transfers")
        Observable<Response<ResponseBody>> list(@Path("billingAccountName") String billingAccountName, @Path("billingProfileName") String billingProfileName, @Path("customerName") String customerName, @Header("accept-language") String acceptLanguage, @Header("User-Agent") String userAgent);

        @Headers({ "Content-Type: application/json; charset=utf-8", "x-ms-logging-context: com.microsoft.azure.management.billing.v2019_10_01_preview.PartnerTransfersTransfers listNext" })
        @GET
        Observable<Response<ResponseBody>> listNext(@Url String nextUrl, @Header("accept-language") String acceptLanguage, @Header("User-Agent") String userAgent);

    }

    /**
     * Lists all transfer's details initiated from given invoice section.
     *
     * @param billingAccountName billing Account Id.
     * @param billingProfileName Billing Profile Id.
     * @param customerName Customer name.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @throws ErrorResponseException thrown if the request is rejected by server
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent
     * @return the PagedList&lt;TransferDetailsInner&gt; object if successful.
     */
    public PagedList<TransferDetailsInner> list(final String billingAccountName, final String billingProfileName, final String customerName) {
        ServiceResponse<Page<TransferDetailsInner>> response = listSinglePageAsync(billingAccountName, billingProfileName, customerName).toBlocking().single();
        return new PagedList<TransferDetailsInner>(response.body()) {
            @Override
            public Page<TransferDetailsInner> nextPage(String nextPageLink) {
                return listNextSinglePageAsync(nextPageLink).toBlocking().single().body();
            }
        };
    }

    /**
     * Lists all transfer's details initiated from given invoice section.
     *
     * @param billingAccountName billing Account Id.
     * @param billingProfileName Billing Profile Id.
     * @param customerName Customer name.
     * @param serviceCallback the async ServiceCallback to handle successful and failed responses.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the {@link ServiceFuture} object
     */
    public ServiceFuture<List<TransferDetailsInner>> listAsync(final String billingAccountName, final String billingProfileName, final String customerName, final ListOperationCallback<TransferDetailsInner> serviceCallback) {
        return AzureServiceFuture.fromPageResponse(
            listSinglePageAsync(billingAccountName, billingProfileName, customerName),
            new Func1<String, Observable<ServiceResponse<Page<TransferDetailsInner>>>>() {
                @Override
                public Observable<ServiceResponse<Page<TransferDetailsInner>>> call(String nextPageLink) {
                    return listNextSinglePageAsync(nextPageLink);
                }
            },
            serviceCallback);
    }

    /**
     * Lists all transfer's details initiated from given invoice section.
     *
     * @param billingAccountName billing Account Id.
     * @param billingProfileName Billing Profile Id.
     * @param customerName Customer name.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the PagedList&lt;TransferDetailsInner&gt; object
     */
    public Observable<Page<TransferDetailsInner>> listAsync(final String billingAccountName, final String billingProfileName, final String customerName) {
        return listWithServiceResponseAsync(billingAccountName, billingProfileName, customerName)
            .map(new Func1<ServiceResponse<Page<TransferDetailsInner>>, Page<TransferDetailsInner>>() {
                @Override
                public Page<TransferDetailsInner> call(ServiceResponse<Page<TransferDetailsInner>> response) {
                    return response.body();
                }
            });
    }

    /**
     * Lists all transfer's details initiated from given invoice section.
     *
     * @param billingAccountName billing Account Id.
     * @param billingProfileName Billing Profile Id.
     * @param customerName Customer name.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the PagedList&lt;TransferDetailsInner&gt; object
     */
    public Observable<ServiceResponse<Page<TransferDetailsInner>>> listWithServiceResponseAsync(final String billingAccountName, final String billingProfileName, final String customerName) {
        return listSinglePageAsync(billingAccountName, billingProfileName, customerName)
            .concatMap(new Func1<ServiceResponse<Page<TransferDetailsInner>>, Observable<ServiceResponse<Page<TransferDetailsInner>>>>() {
                @Override
                public Observable<ServiceResponse<Page<TransferDetailsInner>>> call(ServiceResponse<Page<TransferDetailsInner>> page) {
                    String nextPageLink = page.body().nextPageLink();
                    if (nextPageLink == null) {
                        return Observable.just(page);
                    }
                    return Observable.just(page).concatWith(listNextWithServiceResponseAsync(nextPageLink));
                }
            });
    }

    /**
     * Lists all transfer's details initiated from given invoice section.
     *
    ServiceResponse<PageImpl<TransferDetailsInner>> * @param billingAccountName billing Account Id.
    ServiceResponse<PageImpl<TransferDetailsInner>> * @param billingProfileName Billing Profile Id.
    ServiceResponse<PageImpl<TransferDetailsInner>> * @param customerName Customer name.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the PagedList&lt;TransferDetailsInner&gt; object wrapped in {@link ServiceResponse} if successful.
     */
    public Observable<ServiceResponse<Page<TransferDetailsInner>>> listSinglePageAsync(final String billingAccountName, final String billingProfileName, final String customerName) {
        if (billingAccountName == null) {
            throw new IllegalArgumentException("Parameter billingAccountName is required and cannot be null.");
        }
        if (billingProfileName == null) {
            throw new IllegalArgumentException("Parameter billingProfileName is required and cannot be null.");
        }
        if (customerName == null) {
            throw new IllegalArgumentException("Parameter customerName is required and cannot be null.");
        }
        return service.list(billingAccountName, billingProfileName, customerName, this.client.acceptLanguage(), this.client.userAgent())
            .flatMap(new Func1<Response<ResponseBody>, Observable<ServiceResponse<Page<TransferDetailsInner>>>>() {
                @Override
                public Observable<ServiceResponse<Page<TransferDetailsInner>>> call(Response<ResponseBody> response) {
                    try {
                        ServiceResponse<PageImpl<TransferDetailsInner>> result = listDelegate(response);
                        return Observable.just(new ServiceResponse<Page<TransferDetailsInner>>(result.body(), result.response()));
                    } catch (Throwable t) {
                        return Observable.error(t);
                    }
                }
            });
    }

    private ServiceResponse<PageImpl<TransferDetailsInner>> listDelegate(Response<ResponseBody> response) throws ErrorResponseException, IOException, IllegalArgumentException {
        return this.client.restClient().responseBuilderFactory().<PageImpl<TransferDetailsInner>, ErrorResponseException>newInstance(this.client.serializerAdapter())
                .register(200, new TypeToken<PageImpl<TransferDetailsInner>>() { }.getType())
                .registerError(ErrorResponseException.class)
                .build(response);
    }

    /**
     * Lists all transfer's details initiated from given invoice section.
     *
     * @param nextPageLink The NextLink from the previous successful call to List operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @throws ErrorResponseException thrown if the request is rejected by server
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent
     * @return the PagedList&lt;TransferDetailsInner&gt; object if successful.
     */
    public PagedList<TransferDetailsInner> listNext(final String nextPageLink) {
        ServiceResponse<Page<TransferDetailsInner>> response = listNextSinglePageAsync(nextPageLink).toBlocking().single();
        return new PagedList<TransferDetailsInner>(response.body()) {
            @Override
            public Page<TransferDetailsInner> nextPage(String nextPageLink) {
                return listNextSinglePageAsync(nextPageLink).toBlocking().single().body();
            }
        };
    }

    /**
     * Lists all transfer's details initiated from given invoice section.
     *
     * @param nextPageLink The NextLink from the previous successful call to List operation.
     * @param serviceFuture the ServiceFuture object tracking the Retrofit calls
     * @param serviceCallback the async ServiceCallback to handle successful and failed responses.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the {@link ServiceFuture} object
     */
    public ServiceFuture<List<TransferDetailsInner>> listNextAsync(final String nextPageLink, final ServiceFuture<List<TransferDetailsInner>> serviceFuture, final ListOperationCallback<TransferDetailsInner> serviceCallback) {
        return AzureServiceFuture.fromPageResponse(
            listNextSinglePageAsync(nextPageLink),
            new Func1<String, Observable<ServiceResponse<Page<TransferDetailsInner>>>>() {
                @Override
                public Observable<ServiceResponse<Page<TransferDetailsInner>>> call(String nextPageLink) {
                    return listNextSinglePageAsync(nextPageLink);
                }
            },
            serviceCallback);
    }

    /**
     * Lists all transfer's details initiated from given invoice section.
     *
     * @param nextPageLink The NextLink from the previous successful call to List operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the PagedList&lt;TransferDetailsInner&gt; object
     */
    public Observable<Page<TransferDetailsInner>> listNextAsync(final String nextPageLink) {
        return listNextWithServiceResponseAsync(nextPageLink)
            .map(new Func1<ServiceResponse<Page<TransferDetailsInner>>, Page<TransferDetailsInner>>() {
                @Override
                public Page<TransferDetailsInner> call(ServiceResponse<Page<TransferDetailsInner>> response) {
                    return response.body();
                }
            });
    }

    /**
     * Lists all transfer's details initiated from given invoice section.
     *
     * @param nextPageLink The NextLink from the previous successful call to List operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the PagedList&lt;TransferDetailsInner&gt; object
     */
    public Observable<ServiceResponse<Page<TransferDetailsInner>>> listNextWithServiceResponseAsync(final String nextPageLink) {
        return listNextSinglePageAsync(nextPageLink)
            .concatMap(new Func1<ServiceResponse<Page<TransferDetailsInner>>, Observable<ServiceResponse<Page<TransferDetailsInner>>>>() {
                @Override
                public Observable<ServiceResponse<Page<TransferDetailsInner>>> call(ServiceResponse<Page<TransferDetailsInner>> page) {
                    String nextPageLink = page.body().nextPageLink();
                    if (nextPageLink == null) {
                        return Observable.just(page);
                    }
                    return Observable.just(page).concatWith(listNextWithServiceResponseAsync(nextPageLink));
                }
            });
    }

    /**
     * Lists all transfer's details initiated from given invoice section.
     *
    ServiceResponse<PageImpl<TransferDetailsInner>> * @param nextPageLink The NextLink from the previous successful call to List operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the PagedList&lt;TransferDetailsInner&gt; object wrapped in {@link ServiceResponse} if successful.
     */
    public Observable<ServiceResponse<Page<TransferDetailsInner>>> listNextSinglePageAsync(final String nextPageLink) {
        if (nextPageLink == null) {
            throw new IllegalArgumentException("Parameter nextPageLink is required and cannot be null.");
        }
        String nextUrl = String.format("%s", nextPageLink);
        return service.listNext(nextUrl, this.client.acceptLanguage(), this.client.userAgent())
            .flatMap(new Func1<Response<ResponseBody>, Observable<ServiceResponse<Page<TransferDetailsInner>>>>() {
                @Override
                public Observable<ServiceResponse<Page<TransferDetailsInner>>> call(Response<ResponseBody> response) {
                    try {
                        ServiceResponse<PageImpl<TransferDetailsInner>> result = listNextDelegate(response);
                        return Observable.just(new ServiceResponse<Page<TransferDetailsInner>>(result.body(), result.response()));
                    } catch (Throwable t) {
                        return Observable.error(t);
                    }
                }
            });
    }

    private ServiceResponse<PageImpl<TransferDetailsInner>> listNextDelegate(Response<ResponseBody> response) throws ErrorResponseException, IOException, IllegalArgumentException {
        return this.client.restClient().responseBuilderFactory().<PageImpl<TransferDetailsInner>, ErrorResponseException>newInstance(this.client.serializerAdapter())
                .register(200, new TypeToken<PageImpl<TransferDetailsInner>>() { }.getType())
                .registerError(ErrorResponseException.class)
                .build(response);
    }

}
