/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.appservice.v2018_02_01.implementation;

import com.microsoft.azure.management.appservice.v2018_02_01.HostStatus;
import com.microsoft.azure.arm.model.implementation.WrapperImpl;
import java.util.List;

class HostStatusImpl extends WrapperImpl<HostStatusInner> implements HostStatus {
    private final CertificateRegistrationManager manager;
    HostStatusImpl(HostStatusInner inner, CertificateRegistrationManager manager) {
        super(inner);
        this.manager = manager;
    }

    @Override
    public CertificateRegistrationManager manager() {
        return this.manager;
    }

    @Override
    public List<String> errors() {
        return this.inner().errors();
    }

    @Override
    public String id() {
        return this.inner().id();
    }

    @Override
    public String state() {
        return this.inner().state();
    }

    @Override
    public String version() {
        return this.inner().version();
    }

    @Override
    public String versionDetails() {
        return this.inner().versionDetails();
    }

}
